### ISSUE TITLE
Better documentation of Data Structure needed

### ISSUE THREAD

**Issue by cpulcini** [llooker/gaming_analytics_block#3]
The block looks really promising and interesting, but could you please provide more detailed documentation of the data needed for it to work out of the box? (i.e. all the columns needed with an explanation on the non-trivial one, e.g. `Event Name What is the event that happened?`: what am I supposed to have here? also, is it one single table for install, revenues, actions, sessions events? ) 
Also, if you own some demo data in a standard format those would be pretty useful.

**Comment by ernestoongaro** [comment]
Thanks for this, the manifest file explains this now: https://github.com/llooker/gaming_analytics_block/blob/master/manifest.lkml
